### ISSUE TITLE
Variable undefined

### ISSUE THREAD

**Issue by SgtPooki** [peterkeating/grunt-csscss#12]
On the current project I am working on, there is a _variables.scss file that has all of the variables used throughout our scss.

Any time I try to scan an scss file, it fails when it encounters a variable, because grunt-csscss is unaware of the variables file.

I was thinking there should be some way to pre-load those variables, or maybe append the file to the beginning of each file being checked but I was unable to find a solution.

Is there anything currently available that could help with this problem?

**Comment by peterkeating** [comment]
I'm not too sure of anything our there that could help with this, _grunt-csscss_ is for `.css` files. Instead of scanning the `.scss` files you want to compile the `.scss` files into CSS and then scan those with csscss.

**Comment by SgtPooki** [comment]
@peterkeating please forgive my numerous questions, I'm a backend dev still trying to learn the intricacies of front-end build practices. 

csscss supports scanning sass and less files; is this functionality not in grunt-csscss's future?

Maybe i'm confused but doesn't the 'Analyzing Compass Stylesheet' section in the readme say that it can analyze sass files? What is the use of passing the path of the scss file if you're not going to analyze it?

If you're scanning the css to determine redundancy, isn't this abstracted from the sass far enough to make finding any issues in your scss quite difficult? Or is this easier than I imagine?

**Comment by peterkeating** [comment]
@SgtPooki Apologies you're completely right CSSCSS does handle `.scss` & `.less` files so seeing as `grunt-csscss` is essentially running the CSSCSS command then this grunt task will handle it (been a while since I've worked on this project). Being able to define a variables file to be included at the top of the `.scss` file being scanned isn't part of the project currently and can't see the need for it to be too great, it's quite an odd scenario. I'd imagine you would want to scan the main `.scss` file that imports the `_variables.scss` file as well as any other .scss files that make up the stylesheet, however I'm not familiar with your use case. I'd be interested to know why your looking for it to work this way?

**Comment by SgtPooki** [comment]
I think you just answered my question.. I shouldn't be scanning each file individually, I should only be scanning the global or page level scss files that are importing the others. hah. Thanks!

**Comment by SgtPooki** [comment]
I was looking at this like jscs/jshint and other tools that scan each file individually.. but that won't work in this scenario; I need to scan global.scss and the other page-level/global sass files. Thanks again.
